[package]
name = "aelita"
version = "0.1.0"
authors = ["Michael Holub <michael.holub@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.7.1"
clap = "3.0.0-beta.2"
trait_enum = "0.5.0"